### ISSUE TITLE
not able to add a ticket with labels that have more than 1 word.

### ISSUE THREAD

**Issue by ZBejavu** [zilbers/ticket-manager#2]
If I were to try and create a ticket with the label: 'View Count' I would get two labels : 'View' and 'Count' instead.
the issue is cause by creating the labels from the input string, separating it by the spaces. 
- my suggestion is to make the label field( an input for creating a label that the user wants) and a button beside it to add it to the label list of the Ticket.
- you can add the label list to the ticket creating screen live, and make it clickable (for removing the ticket if it was a mistake)

**Comment by zilbers** [comment]
Fixed
